@startuml
actor Player

participant snake_game order 10
participant rules order 20
participant board order 40
participant snake order 30
participant window order 50
participant ia order 60
participant controller order 70

rules -> snake_game : update()
snake_game -> rules : update()

rules -> snake : get_next_head_position()
snake -> rules : next_head_position

rules -> board : get_block( next_head_position )
alt [ empty block ]
    rules -> snake : move()
    snake -> board : remove_block( tail_position )
    board -> snake
    snake -> board : put_block( next_head_position )
    board -> snake
    snake -> rules
    else [ apple block ]
    rules -> snake : grow()
    snake -> board : put_block( next_head_position )
    board -> snake
    snake -> rules
    rules -> board : get_empty_blocks()
    board -> rules : positions
    rules -> rules : _put_apple()

    else [ snake block or wall block ]
    rules -> snake_game : game_over()
end alt

snake_game -> window : draw(board)

opt [ ai present ]
snake_game -> ia : next_move()
ia -> snake_game : get_board()
snake_game -> ia : board
ia -> snake_game : get_controller()
snake_game -> ia : controller()
ia -> controller : move(direction)
controller -> ia
end


@enduml